#spring.application.name=Journal
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.username=muUsername
#spring.data.mongodb.password=myPassword
#mongodb+srv://cmayur1404_db_user:<db_password>@cluster0.3fhaqhg.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

spring.data.mongodb.uri=mongodb+srv://cmayur1404_db_user:IDBZtZsqT8QDR0JR@cluster0.3fhaqhg.mongodb.net/journaldb?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=journaldb
spring.data.mongodb.auto-index-creation=true