spring:
  data:
    mongodb:
      #uri: mongodb+srv://cmayur1404_db_user:IDBZtZsqT8QDR0JR@cluster0.3fhaqhg.mongodb.net/journaldb?retryWrites=true&w=majority&appName=Cluster0
      uri: ${MONGODB_URI}  # Use environment variable for MongoDB connection
      database: journaldb
      auto-index-creation: true
      connect-timeout: 60000
      socket-timeout: 60000
server:
  address: 0.0.0.0
  port: ${PORT:8080}