spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}  # Use environment variable for MongoDB connection
      database: journaldb
      auto-index-creation: true

server:
  port: ${PORT:8080}  # Render provides dynamic port via this environment variable