spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}  # Use environment variable for MongoDB connection
      database: journaldb
      auto-index-creation: true
      connect-timeout: 60000
      socket-timeout: 60000

server:
  port: ${PORT:8080}  # Render provides dynamic port via this environment variable